name: LA 5.2 Testing exercise

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
        - name: Build with Make
          run: make
        - name: Run Tests
          run: ./test